# Form implementation generated from reading ui file 'D:\hoccode\QT Designer\TEST\doanktlt\ui\MNgamenobonus1.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(478,850)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(250, 20, 301, 511))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_6 = QtWidgets.QFrame(parent=self.gridLayoutWidget_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.widget_2 = QtWidgets.QWidget(parent=self.frame_6)
        self.widget_2.setGeometry(QtCore.QRect(0, 160, 301, 351))
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_2.setObjectName("widget_2")

        # hình ảnh may mắn lần sau
        self.label_image = QtWidgets.QLabel(parent=self.widget_2)
        self.label_image.setGeometry(QtCore.QRect(60, 50, 191, 61))
        self.label_image.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_image.setText("")
        self.label_image.setPixmap(QtGui.QPixmap("D:\\hoccode\\QT Designer\\TEST\\doanktlt\\ui\\../../../../../ktlt_đồ án/pngtree-better-luck-next-time-setback-fail-png-image_10561842.png"))
        self.label_image.setScaledContents(True)
        self.label_image.setObjectName("label_image")

        # chúc mừng may mán lần sau
        self.label_lucknext = QtWidgets.QLabel(parent=self.widget_2)
        self.label_lucknext.setGeometry(QtCore.QRect(40, 130, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_lucknext.setFont(font)
        self.label_lucknext.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)  # Căn giữa
        self.label_lucknext.setObjectName("label_lucknext")

        # button đi tới giỏ hàng
        self.pushButton_gotocart = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_gotocart.setGeometry(QtCore.QRect(60, 240, 181, 28))
        self.pushButton_gotocart.setStyleSheet("background-color: rgb(189, 25, 6);\n"
"color: rgb(255, 255, 255); font-weight: bold")
        self.pushButton_gotocart.setObjectName("pushButton_gotocart")

        # Button back
        self.pushButton_back = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_back.setGeometry(QtCore.QRect(60, 290, 181, 28))
        self.pushButton_back.setStyleSheet("background-color: rgb(189, 25, 6);\n"
"color: rgb(255, 255, 255); font-weight: bold")
        self.pushButton_back.setObjectName("pushButton_back")


        self.frame_7 = QtWidgets.QFrame(parent=self.frame_6)
        self.frame_7.setGeometry(QtCore.QRect(0, 129, 301, 31))
        self.frame_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")

        # tiêu đề
        self.label_title = QtWidgets.QLabel(parent=self.frame_7)
        self.label_title.setGeometry(QtCore.QRect(30, 10, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")


        self.label_26 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 21, 16))
        self.label_26.setObjectName("label_26")

        # hình ảnh minigame chính
        self.label_image_main = QtWidgets.QLabel(parent=self.frame_6)
        self.label_image_main.setGeometry(QtCore.QRect(-10, 0, 311, 131))
        self.label_image_main.setText("")
        self.label_image_main.setPixmap(QtGui.QPixmap("D:\\hoccode\\QT Designer\\TEST\\doanktlt\\ui\\../../../../../ktlt_đồ án/minigame-choi-vui-trung-lon-01590979733.jpg"))
        self.label_image_main.setScaledContents(True)
        self.label_image_main.setObjectName("label_image_main")

        # grid layout
        self.gridLayout_2.addWidget(self.frame_6, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_lucknext.setText(_translate("MainWindow", "Chúc bạn may mắn lần sau "))
        self.pushButton_gotocart.setText(_translate("MainWindow", "Đi tới giỏ hàng"))
        self.pushButton_back.setText(_translate("MainWindow", "Bỏ qua"))
        self.label_title.setText(_translate("MainWindow", "Hộp quà may mắn"))
        self.label_26.setText(_translate("MainWindow", "<"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())