# Form implementation generated from reading ui file 'D:\hoccode\QT Designer\TEST\doanktlt\ui\MNgamebonus1.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(478,850)


        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(270, 20, 301, 511))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_8 = QtWidgets.QFrame(parent=self.gridLayoutWidget_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.widget_3 = QtWidgets.QWidget(parent=self.frame_8)
        self.widget_3.setGeometry(QtCore.QRect(0, 160, 301, 351))
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_3.setObjectName("widget_3")

        # Button đi tới giỏ hàng
        self.pushButton_gotocart = QtWidgets.QPushButton(parent=self.widget_3)
        self.pushButton_gotocart.setGeometry(QtCore.QRect(60, 240, 181, 28))
        self.pushButton_gotocart.setStyleSheet("background-color: rgb(189, 25, 6);\n"
"color: rgb(255, 255, 255); font-weight:bold")
        self.pushButton_gotocart.setObjectName("pushButton_gotocart")

        # Button quay trở lại
        self.pushButton_skip = QtWidgets.QPushButton(parent=self.widget_3)
        self.pushButton_skip.setGeometry(QtCore.QRect(60, 290, 181, 28))
        self.pushButton_skip.setStyleSheet("background-color: rgb(189, 25, 6);\n"
"color: rgb(255, 255, 255); font-weight: bold")
        self.pushButton_skip.setObjectName("pushButton_skip")

        # chúc mừng
        self.label_congratt = QtWidgets.QLabel(parent=self.widget_3)
        self.label_congratt.setGeometry(QtCore.QRect(50, 10, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_congratt.setFont(font)
        self.label_congratt.setStyleSheet("color: rgb(255, 85, 255);")
        self.label_congratt.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)  # Căn giữa
        self.label_congratt.setObjectName("label_congratt")

        # hình ảnh voucher
        self.label_imagvoucher = QtWidgets.QLabel(parent=self.widget_3)
        self.label_imagvoucher.setGeometry(QtCore.QRect(60, 50, 191, 61))
        self.label_imagvoucher.setText("")
        self.label_imagvoucher.setPixmap(QtGui.QPixmap("D:\\hoccode\\QT Designer\\TEST\\doanktlt\\ui\\../../../../../ktlt_đồ án/images.png"))
        self.label_imagvoucher.setScaledContents(True)
        self.label_imagvoucher.setObjectName("label_imagvoucher")

        # label voucher
        self.label_vouchergame = QtWidgets.QLabel(parent=self.widget_3)
        self.label_vouchergame.setGeometry(QtCore.QRect(40, 130, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_vouchergame.setFont(font)
        self.label_vouchergame.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_vouchergame.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)  # Căn giữa
        self.label_vouchergame.setObjectName("label_vouchergame")


        self.label = QtWidgets.QLabel(parent=self.widget_3)
        self.label.setGeometry(QtCore.QRect(110, 170, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_8)
        self.frame_9.setGeometry(QtCore.QRect(0, 129, 301, 31))
        self.frame_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_title = QtWidgets.QLabel(parent=self.frame_9)
        self.label_title.setGeometry(QtCore.QRect(30, 10, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.label_28 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_28.setGeometry(QtCore.QRect(10, 10, 21, 16))
        self.label_28.setObjectName("label_28")

        # label image
        self.label_image = QtWidgets.QLabel(parent=self.frame_8)
        self.label_image.setGeometry(QtCore.QRect(-10, 0, 311, 131))
        self.label_image.setText("")
        self.label_image.setPixmap(QtGui.QPixmap("D:\\hoccode\\QT Designer\\TEST\\doanktlt\\ui\\../../../../../ktlt_đồ án/minigame-choi-vui-trung-lon-01590979733.jpg"))
        self.label_image.setScaledContents(True)
        self.label_image.setObjectName("label_image")


        # gridlayout
        self.gridLayout_3.addWidget(self.frame_8, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_gotocart.setText(_translate("MainWindow", "Đi tới giỏ hàng"))
        self.pushButton_skip.setText(_translate("MainWindow", "Bỏ qua"))
        self.label_congratt.setText(_translate("MainWindow", "Chúc mừng bạn đã nhận được "))
        self.label_vouchergame.setText(_translate("MainWindow", "1 VOUCHER MUA SẮM 50% "))
        self.label.setText(_translate("MainWindow", "#maiyeuuel"))
        self.label_title.setText(_translate("MainWindow", "Hộp quà may mắn"))
        self.label_28.setText(_translate("MainWindow", "<"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())